export * as areaApis from './area/api'
export * as commonApis from './common/api'
export * as departmentApis from './department/api'
export * as loginApis from './login/api'
export * as registerApis from './register/api'
export * as roleApis from './role/api'
export * as userApis from './user/api'
