export * as actualProductionApis from './actualProduction/api'
export * as areaApis from './area/api'
export * as commonApis from './common/api'
export * as departmentApis from './department/api'
export * as dockingDataApis from './dockingData/api' //字典数据
export * as loginApis from './login/api'
export * as practice from './practice/api'
export * as registerApis from './register/api'
export * as roleApis from './role/api'
export * as userApis from './user/api'
